name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Configure Web Support
        run: |
          cd mobile
          flutter create . --platforms web

      - name: Build for GitHub Pages
        run: |
          cd mobile
          flutter build web --web-renderer canvaskit --base-href "/alces-barbearia/" --release

      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mobile/build/web
          publish_branch: gh-pages

      - name: Build for Vercel
        run: |
          cd mobile
          flutter build web --base-href "/" --release

      - name: Deploy to Vercel Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mobile/build/web
          publish_branch: web-preview
